version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-resizer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cldzzvkfxfgk"
s3_prefix = "image-resizer"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SourceBucketName=\"okiyalabs-shop-src-images\" DestinationBucketName=\"okiyalabs-shop-dest-images\""
image_repositories = []
