version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  admin:
    container_name: admin_frontend
    build:
      context: ./frontend/admin_page
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/admin_page:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8003
      - VITE_AUTH_API_URL=http://localhost:8004

  client:
    container_name: client_frontend
    build:
      context: ./frontend/client_page
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./frontend/client_page:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
      - VITE_AUTH_API_URL=http://localhost:8004
      - VITE_CART_URL=http://localhost:8006
      - VITE_CHECKOUT_URL=http://localhost:8007

  # auth-service:
  #   build: ./backend/auth-service
  #   container_name: auth-service
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./backend/auth-service:/app
  #   ports:
  #     - "8001:8000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DATABASE_URL=postgres://ecommerce_user:strongpassword@postgres:5432/ecommerce

  order-service:
    build: ./backend/orders
    container_name: order-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./backend/orders:/app
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    environment:
      - DB_NAME=ecommerce
      - DB_USER=ecommerce_user
      - DB_PASSWORD=strongpassword
      - DB_HOST=postgres  
      - DB_PORT=5432

  product-service:
    build: ./backend/products
    container_name: product-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    volumes:
      - ./backend/products:/app
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    environment:
      - DB_NAME=ecommerce
      - DB_USER=ecommerce_user
      - DB_PASSWORD=strongpassword
      - DB_HOST=postgres  
      - DB_PORT=5432

  user-service:
    build: ./backend/users
    container_name: user-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8004"
    volumes:
      - ./backend/users:/app
      - ~/.aws:/root/.aws:ro
    ports:
      - "8004:8004"
    depends_on:
      - postgres
    environment:
      - DB_NAME=ecommerce
      - DB_USER=ecommerce_user
      - DB_PASSWORD=strongpassword
      - DB_HOST=postgres  
      - DB_PORT=5432

  payment-service:
    build: ./backend/payments
    container_name: payment-service
    command: python manage.py runserver 0.0.0.0:8005
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    environment:
      - DB_NAME=ecommerce
      - DB_USER=ecommerce_user
      - DB_PASSWORD=strongpassword
      - DB_HOST=postgres  
      - DB_PORT=5432    
      - PAYSTACK_SECRET_KEY=sk_test_3d3a69512e465c85fb29b3bedc14ab77d6b943ae
      - PAYMENT_CALLBACK=https://da94-197-248-143-155.ngrok-free.app

  cart-service:
    build: ./backend/cart
    container_name: cart-service
    command: python manage.py runserver 0.0.0.0:8006
    ports:
      - "8006:8006"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CART_TTL_SECONDS=180

  checkout-service:
    build: ./backend/checkout
    container_name: checkout-service
    command: python manage.py runserver 0.0.0.0:8007
    ports:
      - "8007:8007"
    environment:
      - ORDERS_SERVICE_URL=http://order-service:8002
      - PAYMENT_SERVICE_URL=http://payment-service:8005
    depends_on:
      - order-service
      - payment-service  

volumes:
  pgdata:
  redisdata:
