# Generated by Django 5.2 on 2025-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='staff_users',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
