# Generated by Django 5.2 on 2025-11-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adminuser_cognito_username_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='staff',
        ),
    ]
