# Generated by Django 5.2 on 2025-11-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adminuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='staff_users',
        ),
    ]
